### ISSUE TITLE
Errors on  CREATE SCHEMA 

### ISSUE THREAD

**Issue by fijiwebdesign** [duartealexf/sql-ddl-to-json-schema#41]
```
CREATE SCHEMA IF NOT EXISTS `dbname` DEFAULT CHARACTER SET utf8mb4 ;
```

It won't handle `CREATE SCHEMA` or `CREATE DATABASE`. 

Throws on line: 

`sql-ddl-to-json-schema/lib/mysql/formatter/compact/models/database.js:130:15`

```
TypeError: Cannot read property 'setDatabase' of undefined
    at ddsCollection.forEach.dds (/app/local_modules/sql-ddl-to-json-schema/lib/mysql/formatter/compact/models/database.js:130:15)
    at Array.forEach (<anonymous>)
    at Database.parseDdsCollection (/app/local_modules/sql-ddl-to-json-schema/lib/mysql/formatter/compact/models/database.js:91:24)
    at Function.format (/app/local_modules/sql-ddl-to-json-schema/lib/mysql/formatter/compact/index.js:27:14)
    at Parser.toCompactJson (/app/local_modules/sql-ddl-to-json-schema/lib/parser.js:207:34)
    at Parser.toJsonSchemaArray (/app/local_modules/sql-ddl-to-json-schema/lib/parser.js:221:21)
    at Parser.toJsonSchemaFiles (/app/local_modules/sql-ddl-to-json-schema/lib/parser.js:242:26)
    at Object.<anonymous> (/app/local_modules/caminte-cli/lib/sqlparser2.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
```

Debugging that line: 

the value for `json` is: 

```
{ json: { id: 'P_CREATE_DB', def: { database: 'dbname', meta: [Array] } }
```

```
 /**
   * Build tables array from parsed DDL statements by sending them to
   * appropriate handlers, updating tables array after each statement.
   *
   * @param {any[]} ddsCollection DDS statements array.
   * @returns {void}
   */
  parseDdsCollection(ddsCollection) {
    this.ddsCollection = ddsCollection;

    this.ddsCollection.forEach(dds => {

      /**
       * Statements such as SET are supported by parser
       * but are ignored, returning null DDS.
       */
      if (!dds) {
        return;
      }

      const json = dds.def;
      let handler;

      if (json.id === 'P_CREATE_TABLE') {
        handler = new CreateTable();
      }

      else if (json.id === 'P_CREATE_INDEX') {
        handler = new CreateIndex();
      }

      else if (json.id === 'P_ALTER_TABLE') {
        handler = new AlterTable();
      }

      else if (json.id === 'P_RENAME_TABLE') {
        handler = new RenameTable();
      }

      else if (json.id === 'P_DROP_TABLE') {
        handler = new DropTable();
      }

      else if (json.id === 'P_DROP_INDEX') {
        handler = new DropIndex();
      }

      console.log('handler', { json, handler }) // hadnler is undefined as there is no json.id === P_CREATE_DB 

      handler.setDatabase(this);
      handler.handleDef(json);
    });
  }
```

**Comment by fijiwebdesign** [comment]
Maybe it should ignore statements it doesn't have support for? 

If that is a case I could submit a PR for that.

**Comment by duartealexf** [comment]
Thanks :)

Also thanks for elaborating your question.

In my experience writing this parser I can tell you it's actually hard to ignore statements it does not have support for, because:

1. it's really easy to ignore supported stuff;
2. it should know what to ignore, in other words one would have to add the ignorable statements;
3. Once you've done number 2, you're actually starting to support it and not ignore.

Anyways, CREATE DATABASE statement is actually supported:
https://github.com/duartealexf/sql-ddl-to-json-schema/blob/master/src/mysql/parser/lexer.ne#L34
https://github.com/duartealexf/sql-ddl-to-json-schema/blob/master/src/mysql/parser/rules/create-database.ne#L6

The error you pointed is in `sql-ddl-to-json-schema/lib/mysql/formatter` so it did parse and the error is in the formatter.

Could you share the SQL statement that is causing this error? And also can you share the a snippet of the JS code that you used.

Thanks :)

**Comment by duartealexf** [comment]
Hi @fijiwebdesign, i just fixed this.

Check out version 3.0.1 ;)

Thanks!
